import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* bg gray 200 se strt ho k 400 tk ja rha h uper se 200 shade h or bottom
      tk jte 400 ho jae gey */}
      <body className='bg-gradient-to-b from-gray-200 to-gray-400'>{children}</body>
    </html>
  )
}
